### ISSUE TITLE
Fr Translation

### ISSUE THREAD

**Issue by danhype** [ColdTrick/account_removal#10]
Hello,
I made a translation in French of the plugin that you can take back here : https://gitlab.com/dandauge/elgg-current/-/tree/master/mod/account_removal/languages
Dan.

**Comment by jeabakker** [comment]
If you follow this guide you'll get credit for making the translation https://docs.github.com/en/github/managing-files-in-a-repository/adding-a-file-to-a-repository

**Comment by danhype** [comment]
Hello, i create a fr.php file : https://github.com/ColdTrick/account_removal/compare/master...danhype:patch-1

**Comment by jeabakker** [comment]
PR via #11

**Comment by jeabakker** [comment]
thank you
